version: '2'

services:
    iobroker:
        restart: always
        expose:
            - "8081"
        ports:
            - "8010:8081"
        build: iobroker
        volumes:
            - /opt/docker/iobroker/iobroker/opt:/opt/iobroker/
        networks:
            - iobroker-network            
networks:
    iobroker-network:
        driver: bridge

