version: '2'

services:
    iobroker:
        restart: always
        expose:
            - "8081"
            - "8082"
        ports:
            - "8010:8081"
        build: iobroker
        volumes:
            - ./iobroker/opt/:/opt/iobroker/
        networks:
            - iobroker-network
        depends_on:
            - "mysql"
            
networks:
    iobroker-network:
        driver: bridge

